name: Master

on:
  push:
    branches:
      - master

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Write sha
        run: |
          echo "$GITHUB_SHA"
          printf "$GITHUB_SHA" > .application-version
          cat .application-version