name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  test-action:
      runs-on: ubuntu-latest
      steps:
        - name: Write app version
          run: echo "${{ github.event.pull_request.head.ref }}"