name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Write branch
        run: echo "${{ github.event.pull_request.head.ref }}"
      - name: Write sha
        run: |
          echo "$GITHUB_SHA"
          printf "$GITHUB_SHA" > .application-version
          cat .application-version